// Holds the default built-in application themes.
export const DEFAULT_THEMES = [
  {
    id: "aurora",
    name: "Dark Aurora",
    class: "theme-aurora",
    color: "bg-purple-500",
    textGradient: "from-purple-400 to-indigo-400",
    activeBg: "bg-purple-500/20 text-purple-300",
    iconColor: "text-purple-400",
    stroke: "text-purple-500",
  },
  {
    id: "crimson",
    name: "Crimson Void",
    class: "theme-crimson",
    color: "bg-red-500",
    textGradient: "from-red-400 to-orange-400",
    activeBg: "bg-red-500/20 text-red-300",
    iconColor: "text-red-400",
    stroke: "text-red-500",
  },
  {
    id: "emerald",
    name: "Emerald Sea",
    class: "theme-emerald",
    color: "bg-emerald-500",
    textGradient: "from-emerald-400 to-cyan-400",
    activeBg: "bg-emerald-500/20 text-emerald-300",
    iconColor: "text-emerald-400",
    stroke: "text-emerald-500",
  },
  {
    id: "cyber",
    name: "Neon Cyber",
    class: "theme-cyber",
    color: "bg-blue-500",
    textGradient: "from-blue-400 to-fuchsia-400",
    activeBg: "bg-blue-500/20 text-blue-300",
    iconColor: "text-blue-400",
    stroke: "text-blue-500",
  },
  {
    id: "cyberpunk",
    name: "Night City",
    class: "theme-cyberpunk",
    color: "bg-yellow-400",
    textGradient: "from-yellow-400 to-amber-500",
    activeBg: "bg-yellow-400/20 text-yellow-300",
    iconColor: "text-yellow-400",
    stroke: "text-yellow-400",
  },
];
