name: Build and Release Black Pearl

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    name: Build Windows 
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Set App Version from Git Tag
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "Updating app version to $VERSION"
          npm version $VERSION --no-git-tag-version

      - name: Build Frontend
        run: npm run build

      - name: Package & Publish Electron App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --x64 --arm64 --publish always